apiVersion : apps/v1
kind: Deployment
metadata:
  name: testnew1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnew1
  template:
    metadata:
      labels:
        app: testnew1 
    spec:
      containers:
        - name: testnew1 
          image: nancytest.azurecr.io/testnew1
          ports:
          - containerPort: 80